project:
  type: book
  output-dir: docs
  
book:
  title: "Nguyen's Note book"
  author: "Nguyen Pham Nguyen The"
  date: "18/3/2025"
  chapters:
    - index.qmd
    # - intro.qmd
    # - summary.qmd
    - sea_force.qmd
    - references.qmd

toc: true
echo: false

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-copy: true
    fig-format: svg
    toc-expand: 3


editor: visual

